project:
  type: book
  output-dir: _book
  resources: 
    - "img/open_graph.png"

lang: ja
filters: 
  - lightbox
lightbox: auto

book:
  title: "AI総合演習"
  author: "瓜生真也"
  date: "2023/5/12"
  search: true
  reader-mode: true
  google-analytics: "G-57R1KWZ3ZJ"
  twitter-card: 
    creator: "@u_ribo"
    image: "img/open_graph.png"
  open-graph: true
  sharing: [twitter]

  chapters:
    - index.qmd
    - week01/guidance.qmd
    - part: week02/index.qmd
      chapters: 
        - week02/0201_pandas.qmd
        - week02/0202_matplotlib.qmd
    - part: week03/index.qmd
      chapters: 
        - week03/03_mathematics.qmd
    - part: week04/index.qmd
      chapters: 
        - week04/0401_penguins.qmd
        - week04/0402_classification.qmd
    - part: week05/index.qmd
      chapters: 
        - week05/0501_regression.qmd
        - week05/0502_svm.qmd
        - week05/0503_k-means.qmd
    - references.qmd
  appendices:
    - appendix/jupyternotebook.qmd

  site-url: https://uribo.github.io/exeai/
  repo-url: https://github.com/uribo/exeai
  repo-branch: main
  repo-actions: [edit, issue]
  page-footer: 
    background: light
    left: "Copyright 2023, Shinya Uryu"
    right: 
      - icon: github
        href: https://github.com/uribo
      - icon: twitter 
        href: https://twitter.com/u_ribo

bibliography: references.bib
ascii: false

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    code-link: false
    highlight-style: github

license: MIT
